#!/bin/sh

yadm sparse-checkout set --no-cone '/*' '!README.md' '!UNLICENSE.md'

sudo rpm-ostree install --idempotent gcc
command -v gcc || { echo "systemctl reboot is needed"; exit 1; }

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install  \
    eza \
    fzf \
    golang \
    gopass \
    neovim \
    ripgrep \
    rustup \
    tree-sitter
brew install --cask font-fira-code-nerd-font

rustup default stable
rustup-init -y
go env -w GOPATH=$HOME/.local/share/go
