#!/bin/sh

yadm sparse-checkout set --no-cone '/*' '!README.md' '!UNLICENSE.md'

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install  \
    eza \
    fzf \
    golang \
    gopass \
    neovim \
    ripgrep \
    tree-sitter
brew install --cask font-fira-code-nerd-font

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
go env -w GOPATH=$HOME/.local/share/go
